// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1RaTruCbl-ZBDbzCGcNo7QeXOQKsXsCU',
    appId: '1:804280292163:web:0b8aee6ccf79b0213dd5f6',
    messagingSenderId: '804280292163',
    projectId: 'woocommerce-manager-afa50',
    authDomain: 'woocommerce-manager-afa50.firebaseapp.com',
    storageBucket: 'woocommerce-manager-afa50.firebasestorage.app',
    measurementId: 'G-EGJKPVMGMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8fXujeA59Xo_B6jDK5rlLRMdXSBZiY4U',
    appId: '1:804280292163:android:6f44307f899cafc43dd5f6',
    messagingSenderId: '804280292163',
    projectId: 'woocommerce-manager-afa50',
    storageBucket: 'woocommerce-manager-afa50.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1RaTruCbl-ZBDbzCGcNo7QeXOQKsXsCU',
    appId: '1:804280292163:web:e409580d69052c6a3dd5f6',
    messagingSenderId: '804280292163',
    projectId: 'woocommerce-manager-afa50',
    authDomain: 'woocommerce-manager-afa50.firebaseapp.com',
    storageBucket: 'woocommerce-manager-afa50.firebasestorage.app',
    measurementId: 'G-YCY6DBD9FQ',
  );
}
